#pragma kernel GenerateTerrain
#pragma kernel SetTerrainBlocks
#pragma kernel AddOres
#pragma kernel ComputeMesh

#include "Packages/jp.keijiro.noiseshader/Shader/SimplexNoise3D.hlsl"
#include "Packages/jp.keijiro.noiseshader/Shader/ClassicNoise3D.hlsl"


static const float3  VertsNX[4] = { float3(-0.5, -0.5,  0.5), float3(-0.5,  0.5,  0.5), float3(-0.5,  0.5, -0.5), float3(-0.5, -0.5, -0.5)};
static const float3  VertsPX[4] = { float3( 0.5, -0.5,  0.5), float3( 0.5, -0.5, -0.5), float3( 0.5,  0.5, -0.5), float3( 0.5,  0.5,  0.5)};
static const float3  VertsNY[4] = { float3( 0.5, -0.5, -0.5), float3( 0.5, -0.5,  0.5), float3(-0.5, -0.5,  0.5), float3(-0.5, -0.5, -0.5)};
static const float3  VertsPY[4] = { float3( 0.5,  0.5,  0.5), float3( 0.5,  0.5, -0.5), float3(-0.5,  0.5, -0.5), float3(-0.5,  0.5,  0.5)};
static const float3  VertsNZ[4] = { float3( 0.5, -0.5, -0.5), float3(-0.5, -0.5, -0.5), float3(-0.5,  0.5, -0.5), float3( 0.5,  0.5, -0.5)};
static const float3  VertsPZ[4] = { float3(-0.5, -0.5,  0.5), float3( 0.5, -0.5,  0.5), float3( 0.5,  0.5,  0.5), float3(-0.5,  0.5,  0.5)};

static const float3  NormNX = float3(-1.0, 0.0, 0.0);
static const float3  NormPX = float3( 1.0, 0.0, 0.0);
static const float3  NormNY = float3( 0.0,-1.0, 0.0);
static const float3  NormPY = float3( 0.0, 1.0, 0.0);
static const float3  NormNZ = float3( 0.0, 0.0,-1.0);
static const float3  NormPZ = float3( 0.0, 0.0, 1.0);

static const float2  TexNX2[4] = { float2(0.001, 0.749), float2(0.249, 0.749), float2(0.249, 0.501), float2(0.001, 0.501)};
static const float2  TexPX2[4] = { float2(0.501, 0.749), float2(0.749, 0.749), float2(0.749, 0.501), float2(0.501, 0.501)};
static const float2  TexNY2[4] = { float2(0.251, 0.499), float2(0.499, 0.499), float2(0.499, 0.251), float2(0.251, 0.251)};
static const float2  TexPY2[4] = { float2(0.251, 0.999), float2(0.499, 0.999), float2(0.499, 0.751), float2(0.251, 0.751)};
static const float2  TexNZ2[4] = { float2(0.251, 0.749), float2(0.499, 0.749), float2(0.499, 0.501), float2(0.251, 0.501)};
static const float2  TexPZ2[4] = { float2(0.751, 0.749), float2(0.999, 0.749), float2(0.999, 0.501), float2(0.751, 0.501)};

static const float2  TexNX[4] = { float2(0.001, 0.001), float2(0.001, 0.999), float2(0.999, 0.999), float2(0.999, 0.001) };
static const float2  TexPX[4] = { float2(0.001, 0.999), float2(0.999, 0.999), float2(0.999, 0.001), float2(0.001, 0.001) };
static const float2  TexNY[4] = { float2(0.001, 0.001), float2(0.001, 0.999), float2(0.999, 0.999), float2(0.999, 0.001) };
static const float2  TexPY[4] = { float2(0.001, 0.001), float2(0.001, 0.999), float2(0.999, 0.999), float2(0.999, 0.001) };
static const float2  TexNZ[4] = { float2(0.001, 0.999), float2(0.999, 0.999), float2(0.999, 0.001), float2(0.001, 0.001) };
static const float2  TexPZ[4] = { float2(0.001, 0.999), float2(0.999, 0.999), float2(0.999, 0.001), float2(0.001, 0.001) };


static const float4 idColors[4] = {
    float4(0., 0., 0., 1.),
    float4(1., 0., 0., 1.),
    float4(2., 0., 0., 1.),
    float4(3., 0., 0., 1.)
};

struct VoxelData 
{
    uint ID;
    uint Damage;
    uint Orientation;
};

// Map from a 3D voxel pos to an index in the flat voxel buffer
int ComputeIndex(uint3 pos, uint3 size) { 
    return pos.x + size.x * pos.y + size.x * size.y * pos.z;
}

VoxelData NewVoxelData(uint id, uint damage, uint orientation) {
    VoxelData result;
    result.ID = id;
    result.Damage = damage;
    result.Orientation = orientation;
    return result;
}



RWStructuredBuffer<int> VoxelIDs;
RWStructuredBuffer<VoxelData> Voxels;

uint3 Size;
float Scale;
float Threshold;
float3 TranslateNoise;

[numthreads(16,4,16)]
void GenerateTerrain (uint3 id : SV_DispatchThreadID)
{
    for (uint y=0; y<Size.y; y++) {
        uint3 pos = uint3(id.x % Size.x, y, id.z % Size.z);
        int index = ComputeIndex(pos, Size);

        float n = SimplexNoise((float3(pos.x,0.,pos.z) + TranslateNoise) * Scale);
        float yRamp = pow(1-(float(y) / Size.y), 2.);

        float t = yRamp;
        t += n * 0.1;

        

        if (t > 0.5) {
            VoxelIDs[index] = 3; 
        } else {
            VoxelIDs[index] = 0; 
        }

        //if (voxelID == 1 && y < Size.y-1) { // put dirt under grass
        //    if(Voxels[ComputeIndex(pos + uint3(0,1,0), Size)] > 0) {
        //        voxelID = 2;
        //    } 
        //}
        //Voxels[index] = 1;
    }
}   



[numthreads(16,4,16)]
void SetTerrainBlocks (uint3 id : SV_DispatchThreadID) {
    for (uint y=0; y<Size.y; y++) {
        uint3 pos = uint3(id.x % Size.x, y, id.z % Size.z);

        int index = ComputeIndex(pos, Size);

        int voxel = VoxelIDs[index];
        int voxel_up1 = VoxelIDs[ComputeIndex(pos + uint3(0,1,0), Size)];

        int index_down1 = ComputeIndex(pos + uint3(0,-1,0), Size);
        int index_down2 = ComputeIndex(pos + uint3(0,-2,0), Size);

        if (voxel > 0) {
            
            if (y == Size.y-1 || voxel_up1 == 0) {
                VoxelIDs[index] = 1;

                for (uint i=1; i<4; i++) {
                    if (y > i-1) {
                        VoxelIDs[ComputeIndex(pos + uint3(0,-1 * i,0), Size)] = 2;
                    }
                }
                
            } else {
                float n = SimplexNoise((pos + TranslateNoise) * Scale * 3.);
                if (n < -0.3) {
                    VoxelIDs[index] = 4;
                }
            }
        }

    }
}

[numthreads(16,4,16)]
void AddOres (uint3 id : SV_DispatchThreadID) {\

    for (uint y=0; y<Size.y; y++) {
        uint3 pos = uint3(id.x % Size.x, y, id.z % Size.z);
        int index = ComputeIndex(pos, Size);

        if (VoxelIDs[index] == 3) {
            float n = SimplexNoise(pos * 100.);
            if (n < 0.00001) {
                VoxelIDs[index] = 6;
            }
        }
    }
        
}


RWStructuredBuffer<float3> Vertices;
RWStructuredBuffer<float3> Normals;
RWStructuredBuffer<float4> Colors;
RWStructuredBuffer<float2> TexCoords;
RWStructuredBuffer<int> ValidIndices;

[numthreads(16,1,16)]
void ComputeMesh (uint3 id : SV_DispatchThreadID)
{
    // Each thread represents one vertical column
    for (uint y=0; y<Size.y; y++) {

        uint3 pos = uint3(id.x % Size.x, y, id.z % Size.z);
        uint voxIndex = ComputeIndex(pos, Size);
        uint voxelID = Voxels[voxIndex].ID;  


        if (voxelID > 0) { // only run if voxel is not empty
            
           uint voxelDamage = Voxels[voxIndex].Damage;
           //uint voxelOrientation = Voxels[voxIndex].Orientation;
           
           // Check value of 6 adjacent voxels, and if current voxel is on chunk edge
           
           uint vox_nx = 0;
           uint vox_px = 0;
           uint vox_ny = 0;
           uint vox_py = 0;
           uint vox_nz = 0;
           uint vox_pz = 0;
           
           if (pos.x > 0) {
               vox_nx = Voxels[ComputeIndex(pos + NormNX, Size)].ID;
           }
           if (pos.x < Size.x - 1){
               vox_px = Voxels[ComputeIndex(pos + NormPX, Size)].ID;
           }
           if (pos.y > 0) {
               vox_ny = Voxels[ComputeIndex(pos + NormNY, Size)].ID;
           }
           if (pos.y < Size.y - 1){
               vox_py = Voxels[ComputeIndex(pos + NormPY, Size)].ID;
           }
           if (pos.z > 0) {
               vox_nz = Voxels[ComputeIndex(pos + NormNZ, Size)].ID;
           }
           if (pos.z < Size.z - 1){
               vox_pz = Voxels[ComputeIndex(pos + NormPZ, Size)].ID;
           }
           
           //float2 texTop[4] = TexPY;
           //float2 texBot[4] = TexNY;
           //float2 texLeft[4] = TexNX;
           //float2 texRight[4] = TexPX;
           //float2 texFront[4] = TexPZ;
           //float2 texBack[4] = TexNZ;
           //
           //// default is +Y
           //if (voxelOrientation == 1) { // -Y
           //    texTop = TexNY;
           //    texBot = TexPY;
           //}
            


            // If adjacent voxel is empty, add a face
            
            uint index = 24 * voxIndex; // map from index in Voxel buffer to index in vertex buffer, which has 24 spaces per Voxel (6 faces * 4 verts)
            
            float4 faceColor = float4(voxelID, 0., voxelDamage, 1.);
            
           // float3 posOffset = float3(0.499,0.499,0.499);
            float3 posOffset = float3(0.0,0.0,0.0);
            
            int n = 0;
            if (vox_nx == 0) {
                // Loop 4 times to add all 4 verts per face
                n = 0;
                for(int i=0; i<4; i++) {

                    Vertices[index + i] = VertsNX[n] + pos + posOffset;
                    Normals[index + i] = NormNX;
                    faceColor.y = 0.;
                    Colors[index + i] = faceColor;
                    TexCoords[index + i] = TexNX[3-n];// + float2(voxel, 0.);
                    n++;
                    ValidIndices[index + i] = 1;
                }
            }
            if (vox_px == 0) {
                n = 0;
                for(int i=4; i<8; i++) {
                    Vertices[index + i] = VertsPX[n] + pos + posOffset;
                    Normals[index + i] = NormPX;
                    faceColor.y = 1.;
                    Colors[index + i] = faceColor;
                    TexCoords[index + i] = TexPX[3-n];// + float2(voxel, 0.);
                    n++;
                    ValidIndices[index + i] = 1;
                }
            }
            if (vox_ny == 0) {
                n = 0;
                for(int i=8; i<12; i++) {
                    Vertices[index + i] = VertsNY[n] + pos + posOffset;
                    Normals[index + i] = NormNY;
                    faceColor.y = 2.;
                    Colors[index + i] = faceColor;
                    TexCoords[index + i] = TexNY[3-n];// + float2(voxel, 0.);
                    n++;
                    ValidIndices[index + i] = 1;
                }
            }
            if (vox_py == 0) {
                n = 0;
                for(int i=12; i<16; i++) {
                    Vertices[index + i] = VertsPY[n] + pos + posOffset;
                    Normals[index + i] = NormPY;
                    faceColor.y = 3.;
                    Colors[index + i] = faceColor;
                    TexCoords[index + i] = TexPY[3-n];// + float2(voxel, 0.);
                    n++;
                    ValidIndices[index + i] = 1;
                }
            }
            if (vox_nz == 0) {
                n = 0;
                for(int i=16; i<20; i++) {
                    Vertices[index + i] = VertsNZ[n] + pos + posOffset;
                    Normals[index + i] = NormNZ;
                    faceColor.y = 4.;
                    Colors[index + i] = faceColor;
                    TexCoords[index + i] = TexNZ[3-n];// + float2(voxel, 0.);
                    n++;
                    ValidIndices[index + i] = 1;
                }
            }
            if (vox_pz == 0) {
                n = 0;
                for(int i=20; i<24; i++) {
                    Vertices[index + i] = VertsPZ[n] + pos + posOffset;
                    Normals[index + i] = NormPZ;
                    faceColor.y = 5.;
                    Colors[index + i] = faceColor;
                    TexCoords[index + i] = TexPZ[3-n];// + float2(voxel, 0.);
                    n++;
                    ValidIndices[index + i] = 1;
                }
            }
        }
    }
}
