#pragma kernel GenerateTerrain
#pragma kernel SetTerrainBlocks
#pragma kernel AddOres
#pragma kernel ComputeMesh

#include "Packages/jp.keijiro.noiseshader/Shader/SimplexNoise3D.hlsl"
#include "Packages/jp.keijiro.noiseshader/Shader/ClassicNoise3D.hlsl"


static const float3  VertsNX[4] = {float3(-0.5, -0.5,  0.5), float3(-0.5,  0.5,  0.5), float3(-0.5,  0.5, -0.5), float3(-0.5, -0.5, -0.5)};
static const float3  VertsPX[4] = {float3( 0.5, -0.5,  0.5), float3( 0.5, -0.5, -0.5), float3( 0.5,  0.5, -0.5), float3( 0.5,  0.5,  0.5)};
static const float3  VertsNY[4] = {float3( 0.5, -0.5, -0.5), float3( 0.5, -0.5,  0.5), float3(-0.5, -0.5,  0.5), float3(-0.5, -0.5, -0.5)};
static const float3  VertsPY[4] = {float3( 0.5,  0.5,  0.5), float3( 0.5,  0.5, -0.5), float3(-0.5,  0.5, -0.5), float3(-0.5,  0.5,  0.5)};
static const float3  VertsNZ[4] = {float3( 0.5, -0.5, -0.5), float3(-0.5, -0.5, -0.5), float3(-0.5,  0.5, -0.5), float3( 0.5,  0.5, -0.5)};
static const float3  VertsPZ[4] = {float3(-0.5, -0.5,  0.5), float3( 0.5, -0.5,  0.5), float3( 0.5,  0.5,  0.5), float3(-0.5,  0.5,  0.5)};
static const float3 FaceVerts[6][4] = {
    {float3(-0.5, -0.5,  0.5), float3(-0.5,  0.5,  0.5), float3(-0.5,  0.5, -0.5), float3(-0.5, -0.5, -0.5)},
    {float3( 0.5, -0.5,  0.5), float3( 0.5, -0.5, -0.5), float3( 0.5,  0.5, -0.5), float3( 0.5,  0.5,  0.5)},
    {float3( 0.5, -0.5, -0.5), float3( 0.5, -0.5,  0.5), float3(-0.5, -0.5,  0.5), float3(-0.5, -0.5, -0.5)},
    {float3( 0.5,  0.5,  0.5), float3( 0.5,  0.5, -0.5), float3(-0.5,  0.5, -0.5), float3(-0.5,  0.5,  0.5)},
    {float3( 0.5, -0.5, -0.5), float3(-0.5, -0.5, -0.5), float3(-0.5,  0.5, -0.5), float3( 0.5,  0.5, -0.5)},
    {float3(-0.5, -0.5,  0.5), float3( 0.5, -0.5,  0.5), float3( 0.5,  0.5,  0.5), float3(-0.5,  0.5,  0.5)}
};

static const float3  NormNX = float3(-1.0, 0.0, 0.0);
static const float3  NormPX = float3( 1.0, 0.0, 0.0);
static const float3  NormNY = float3( 0.0,-1.0, 0.0);
static const float3  NormPY = float3( 0.0, 1.0, 0.0);
static const float3  NormNZ = float3( 0.0, 0.0,-1.0);
static const float3  NormPZ = float3( 0.0, 0.0, 1.0);
static const float3 FaceNorms[6] = {
    float3(-1.0, 0.0, 0.0),
    float3( 1.0, 0.0, 0.0),
    float3( 0.0,-1.0, 0.0),
    float3( 0.0, 1.0, 0.0),
    float3( 0.0, 0.0,-1.0),
    float3( 0.0, 0.0, 1.0)
};

static const float2  TexNX[4] = { float2(0.001, 0.001), float2(0.001, 0.999), float2(0.999, 0.999), float2(0.999, 0.001) };
static const float2  TexPX[4] = { float2(0.001, 0.999), float2(0.999, 0.999), float2(0.999, 0.001), float2(0.001, 0.001) };
static const float2  TexNY[4] = { float2(0.001, 0.001), float2(0.001, 0.999), float2(0.999, 0.999), float2(0.999, 0.001) };
static const float2  TexPY[4] = { float2(0.001, 0.001), float2(0.001, 0.999), float2(0.999, 0.999), float2(0.999, 0.001) };
static const float2  TexNZ[4] = { float2(0.001, 0.999), float2(0.999, 0.999), float2(0.999, 0.001), float2(0.001, 0.001) };
static const float2  TexPZ[4] = { float2(0.001, 0.999), float2(0.999, 0.999), float2(0.999, 0.001), float2(0.001, 0.001) };
static const float2 FaceTex[6][4] =
{
    { float2(0.001, 0.001), float2(0.001, 0.999), float2(0.999, 0.999), float2(0.999, 0.001) },
    { float2(0.001, 0.999), float2(0.999, 0.999), float2(0.999, 0.001), float2(0.001, 0.001) },
    { float2(0.001, 0.001), float2(0.001, 0.999), float2(0.999, 0.999), float2(0.999, 0.001) },
    { float2(0.001, 0.001), float2(0.001, 0.999), float2(0.999, 0.999), float2(0.999, 0.001) },
    { float2(0.001, 0.999), float2(0.999, 0.999), float2(0.999, 0.001), float2(0.001, 0.001) },
    { float2(0.001, 0.999), float2(0.999, 0.999), float2(0.999, 0.001), float2(0.001, 0.001) }
};

static const float4 idColors[4] = {
    float4(0., 0., 0., 1.),
    float4(1., 0., 0., 1.),
    float4(2., 0., 0., 1.),
    float4(3., 0., 0., 1.)
};

struct VoxelData 
{
    uint ID;
    uint Damage;
    uint Orientation;
};

// Map from a 3D voxel pos to an index in the flat voxel buffer
int ComputeIndex(uint3 pos, uint3 size) { 
    return pos.x + size.x * pos.y + size.x * size.y * pos.z;
}

VoxelData NewVoxelData(uint id, uint damage, uint orientation) {
    VoxelData result;
    result.ID = id;
    result.Damage = damage;
    result.Orientation = orientation;
    return result;
}




RWStructuredBuffer<int> VoxelIDs;
RWStructuredBuffer<VoxelData> Voxels;

uint3 Size;
float Scale;
float Threshold;
float3 TranslateNoise;

[numthreads(16,1,16)]
void GenerateTerrain (uint3 id : SV_DispatchThreadID)
{
    uint3 pos = uint3(id.x % Size.x, id.y % Size.y, id.z % Size.z);
    int index = ComputeIndex(pos, Size);

    float n = SimplexNoise((float3(pos.x,0.,pos.z) + TranslateNoise) * Scale);
    float yRamp = pow(1-(float(pos.y) / Size.y), 2.);

    float t = yRamp;
    t += n * 0.1;

        

    if (t > 0.5) {
        VoxelIDs[index] = 3; 
    } else {
        VoxelIDs[index] = 0; 
    }

    //if (voxelID == 1 && y < Size.y-1) { // put dirt under grass
    //    if(Voxels[ComputeIndex(pos + uint3(0,1,0), Size)] > 0) {
    //        voxelID = 2;
    //    } 
    //}
    //Voxels[index] = 1;
    
}   



[numthreads(16,1,16)]
void SetTerrainBlocks (uint3 id : SV_DispatchThreadID) {
    uint3 pos = uint3(id.x % Size.x, id.y % Size.y, id.z % Size.z);

    int index = ComputeIndex(pos, Size);

    int voxel = VoxelIDs[index];
    int voxel_up1 = VoxelIDs[ComputeIndex(pos + uint3(0,1,0), Size)];

    int index_down1 = ComputeIndex(pos + uint3(0,-1,0), Size);
    int index_down2 = ComputeIndex(pos + uint3(0,-2,0), Size);

    if (voxel > 0) {
            
        if (pos.y == Size.y-1 || voxel_up1 == 0) {
            VoxelIDs[index] = 1;

            for (uint i=1; i<4; i++) {
                if (pos.y > i-1) {
                    VoxelIDs[ComputeIndex(pos + uint3(0,-1 * i,0), Size)] = 2;
                }
            }
                
        } else {
            float n = SimplexNoise((pos + TranslateNoise) * Scale * 3.);
            if (n < -0.3) {
                VoxelIDs[index] = 4;
            }
        }
    }

    
}

[numthreads(16,1,16)]
void AddOres (uint3 id : SV_DispatchThreadID) {

    uint3 pos = uint3(id.x % Size.x, id.y % Size.y, id.z % Size.z);
    int index = ComputeIndex(pos, Size);

    if (VoxelIDs[index] == 3) {
        float n = SimplexNoise(pos * 100.);
        if (n < 0.00001) {
            VoxelIDs[index] = 6;
        }
    }
        
}


RWStructuredBuffer<float3> Vertices;
RWStructuredBuffer<float3> Normals;
RWStructuredBuffer<float4> Colors;
RWStructuredBuffer<float2> TexCoords;
RWStructuredBuffer<int> ValidIndices;
RWStructuredBuffer<int> Indices;

[numthreads(16,1,16)]
void ComputeMesh (uint3 id : SV_DispatchThreadID)
{


    //uint3 pos = uint3(id.x % Size.x, y, id.z % Size.z);
    uint3 pos = uint3(id.x % Size.x, id.y % Size.y, id.z % Size.z);
    uint voxIndex = ComputeIndex(pos, Size);
    uint voxelID = Voxels[voxIndex].ID;  


    if (voxelID > 0) { // only run if voxel is not empty
            
        uint voxelDamage = Voxels[voxIndex].Damage;
        //uint voxelOrientation = Voxels[voxIndex].Orientation;
           
        // Check value of 6 adjacent voxels, and if current voxel is on chunk edge
        uint faceBorders[6] = { 0, 0, 0, 0, 0, 0 };

        if (pos.x > 0) {
            faceBorders[0] = Voxels[ComputeIndex(pos + NormNX, Size)].ID;
        }
        if (pos.x < Size.x - 1){
            faceBorders[1] = Voxels[ComputeIndex(pos + NormPX, Size)].ID;
        }
        if (pos.y > 0) {
            faceBorders[2] = Voxels[ComputeIndex(pos + NormNY, Size)].ID;
        }
        if (pos.y < Size.y - 1){
            faceBorders[3] = Voxels[ComputeIndex(pos + NormPY, Size)].ID;
        }
        if (pos.z > 0) {
            faceBorders[4] = Voxels[ComputeIndex(pos + NormNZ, Size)].ID;
        }
        if (pos.z < Size.z - 1){
            faceBorders[5] = Voxels[ComputeIndex(pos + NormPZ, Size)].ID;
        }


        // If adjacent voxel is empty, add a face
            
        uint index = 0; // map from index in Voxel buffer to index in vertex buffer, which has 24 spaces per Voxel (6 faces * 4 verts)
        uint index2 = 0;
        
        
        float4 faceColor = float4(voxelID, 0., voxelDamage, 1.);
            
        // float3 posOffset = float3(0.499,0.499,0.499);
        float3 posOffset = float3(0.0,0.0,0.0);
                    
        for (int f = 0; f < 6; f++)
        {
            if (faceBorders[f] == 0)
            {
                int newIndices[4] = { 0, 1, 2, 3 };
                for (int i = 0; i < 4; i++)
                {
                    index = Vertices.IncrementCounter();
                    //newIndices[i] = index;
                    Vertices[index] = FaceVerts[f][i] + pos;
                    Normals[index] = FaceNorms[f];
                    Colors[index] = float4(faceColor.x, 0., faceColor.z, faceColor.w);
                    TexCoords[index] = FaceTex[f][3 - i];
                    ValidIndices[index] = 1;
                }
                
                Indices[Indices.IncrementCounter()] = newIndices[0];
                Indices[Indices.IncrementCounter()] = newIndices[1];
                Indices[Indices.IncrementCounter()] = newIndices[2];
                Indices[Indices.IncrementCounter()] = newIndices[0];
                Indices[Indices.IncrementCounter()] = newIndices[2];
                Indices[Indices.IncrementCounter()] = newIndices[3];
            }
        }
        
        //int n = 0;
        //if (vox_nx == 0) {
        //    // Loop 4 times to add all 4 verts per face
        //    for(int i=0; i<4; i++) {
        //        index = Vertices.IncrementCounter();
        //        Vertices[index] = VertsNX[i] + pos;
        //        Normals[index] = NormNX;
        //        Colors[index] = float4(faceColor.x, 0., faceColor.z, faceColor.w);
        //        TexCoords[index] = TexNX[3 - i];
        //        ValidIndices[index] = 1;
        //    }
        //    Indices[index2] = index - 4; // 0
        //    Indices[index2] = index - 3; // 1
        //    Indices[index2] = index - 2; // 2
        //    Indices[index2] = index - 4; // 0
        //    Indices[index2] = index - 2; // 2
        //    Indices[index2] = index - 1; // 3
            
        //}
        //if (vox_px == 0) {
        //    for (int i = 0; i < 4; i++)
        //    {
        //        index = Vertices.IncrementCounter();
        //        Vertices[index] = VertsPX[i] + pos;
        //        Normals[index] = NormPX;
        //        Colors[index] = float4(faceColor.x, 1., faceColor.z, faceColor.w);
        //        TexCoords[index] = TexPX[3 - i];
        //        ValidIndices[index] = 1;
        //    }
        //    Indices[index2] = index - 4; // 0
        //    Indices[index2] = index - 3; // 1
        //    Indices[index2] = index - 2; // 2
        //    Indices[index2] = index - 4; // 0
        //    Indices[index2] = index - 2; // 2
        //    Indices[index2] = index - 1; // 3
        //}
        //if (vox_ny == 0) {
        //    for (int i = 0; i < 4; i++)
        //    {
        //        index = Vertices.IncrementCounter();
        //        Vertices[index] = VertsNY[i] + pos;
        //        Normals[index] = NormNY;
        //        Colors[index] = float4(faceColor.x, 2., faceColor.z, faceColor.w);
        //        TexCoords[index] = TexNY[3 - i];
        //        ValidIndices[index] = 1;
        //    }
        //    Indices[index2] = index - 4; // 0
        //    Indices[index2] = index - 3; // 1
        //    Indices[index2] = index - 2; // 2
        //    Indices[index2] = index - 4; // 0
        //    Indices[index2] = index - 2; // 2
        //    Indices[index2] = index - 1; // 3
        //}
        //if (vox_py == 0) {
        //    for (int i = 0; i < 4; i++)
        //    {
        //        index = Vertices.IncrementCounter();
        //        Vertices[index] = VertsPY[i] + pos;
        //        Normals[index] = NormPY;
        //        Colors[index] = float4(faceColor.x, 3., faceColor.z, faceColor.w);
        //        TexCoords[index] = TexPY[3 - i];
        //        ValidIndices[index] = 1;
        //    }
        //    Indices[index2] = index - 4; // 0
        //    Indices[index2] = index - 3; // 1
        //    Indices[index2] = index - 2; // 2
        //    Indices[index2] = index - 4; // 0
        //    Indices[index2] = index - 2; // 2
        //    Indices[index2] = index - 1; // 3
        //}
        //if (vox_nz == 0) {
        //    for (int i = 0; i < 4; i++)
        //    {
        //        index = Vertices.IncrementCounter();
        //        Vertices[index] = VertsNZ[i] + pos;
        //        Normals[index] = NormNZ;
        //        Colors[index] = float4(faceColor.x, 4., faceColor.z, faceColor.w);
        //        TexCoords[index] = TexNZ[3 - i];
        //        ValidIndices[index] = 1;
        //    }
        //    Indices[index2] = index - 4; // 0
        //    Indices[index2] = index - 3; // 1
        //    Indices[index2] = index - 2; // 2
        //    Indices[index2] = index - 4; // 0
        //    Indices[index2] = index - 2; // 2
        //    Indices[index2] = index - 1; // 3
        //}
        //if (vox_pz == 0) {
        //    for (int i = 0; i < 4; i++)
        //    {
        //        index = Vertices.IncrementCounter();
        //        Vertices[index] = VertsPZ[i] + pos;
        //        Normals[index] = NormPZ;
        //        Colors[index] = float4(faceColor.x, 5., faceColor.z, faceColor.w);
        //        TexCoords[index] = TexPZ[3 - i];
        //        ValidIndices[index] = 1;
        //    }
        //    Indices[index2] = index - 4; // 0
        //    Indices[index2] = index - 3; // 1
        //    Indices[index2] = index - 2; // 2
        //    Indices[index2] = index - 4; // 0
        //    Indices[index2] = index - 2; // 2
        //    Indices[index2] = index - 1; // 3
        //}
    }
    
}
